{
 "title": "CCS Data Visualizer TEST",
 "time": { "from": "2023-02-16T08:07:41.000Z", "to": "2023-02-16T08:28:35.000Z" },
 "templating": {
  "list": [
   { "name": "unitIdSelect", "query": "SELECT unitid FROM tblccsunit" },
   { "name": "dataLimit", "query": "250" }
  ]
 },
 "panels": [
  {
   "title": "CFM Unit Dynamic Gauge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "flowcfm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ccs",
     "rawSql": "SELECT \r\n  cfm, \r\n  updateReceived, \r\n  CONCAT(unitIdRef, '') as metric,\r\n  description\r\nFROM ccs.tblccsunitdata \r\nd INNER JOIN ccs.tblccsunit u ON d.unitIdRef = u.unitId\r\nWHERE unitIdRef IN (${unitIdSelect:sqlstring}) \r\nORDER BY updateReceived DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Filter for $unitIdSelect",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dataset": "ccs",
     "rawSql": "SELECT \r\n  updateReceived,\r\n  filterLife, \r\n  CONCAT(unitIdRef, '') as metric,\r\n  description\r\nFROM ccs.tblccsunitdata\r\nd INNER JOIN ccs.tblccsunit u ON d.unitIdRef = u.unitId\r\nWHERE unitIdRef IN (${unitIdSelect:sqlstring})\r\nORDER BY updateReceived DESC \r\nLIMIT ${dataLimit}"
    }
   ]
  },
  {
   "title": "CFM for $unitIdSelect",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "ccs",
     "rawSql": "SELECT \r\n  updateReceived,\r\n  cfm, \r\n  CONCAT(unitIdRef, '') as metric,\r\n  description\r\nFROM ccs.tblccsunitdata\r\nd INNER JOIN ccs.tblccsunit u ON d.unitIdRef = u.unitId\r\nWHERE unitIdRef IN (${unitIdSelect:sqlstring})\r\nORDER BY updateReceived DESC \r\nLIMIT ${dataLimit}"
    }
   ]
  },
  {
   "title": "Temperature (°C) for $unitIdSelect",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "ccs",
     "rawSql": "SELECT \r\n  updateReceived,\r\n  temperature, \r\n  CONCAT(unitIdRef, '') as metric,\r\n  description\r\nFROM ccs.tblccsunitdata\r\nd INNER JOIN ccs.tblccsunit u ON d.unitIdRef = u.unitId\r\nWHERE unitIdRef IN (${unitIdSelect:sqlstring})\r\nORDER BY updateReceived DESC \r\nLIMIT ${dataLimit}"
    }
   ]
  }
 ]
}