version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout

      # Setup Docker Compose
      - setup_remote_docker:
          version: 20.10.7

      # Restore cache for dependencies if exists
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "docker-compose.yml" }}
            - v1-dependencies-

      # Install Docker Compose
      - run:
          name: Install Docker Compose
          command: sudp apt-get update && sudo apt install docker-compose

      # Build and run Docker Compose services
      - run:
          name: Build and Run Docker Compose
          command: docker-compose up -d 
     

      # Save cache for dependencies
      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "docker-compose.yml" }}

      # Persist artifacts
      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
