name: CD

# Only trigger, when the pull workflow succeeded
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  notify:
    runs-on: self-hosted

   

    steps:
      - id: permission
        run: sudo chown -R $USER:$USER /home/ubuntu/actions-runner/_work/amtechtest
        
      - uses: actions/checkout@v3

      - name: Deploy Image
      # pull docker image.
        run: sudo docker-compose pull
        
      - name: docker stop
        # stop and down all the containers running.
        run: sudo docker-compose down
        
      - name: image remove ccs-backend
        run: sudo docker image rm ccs-backend  
      
      - name: image remove css-frontend 
        run: sudo docker image rm ccs-frontend
      
      - name: image remove amtechtest_nginx
        run: sudo docker image rm amtechtest_nginx

      - name: image remove ws-server image
        run: sudo docker image rm ws-server

     # - name: image remove node image
      #  run: sudo docker image rm node

      - name: image remove nginx 
        run: sudo docker image rm nginx  

      - name: image remove grafana 
        run: sudo docker image rm grafana/grafana
        
      - name: docker start
        # start and up all the containers.
        run: sudo docker-compose up -d
