name: CI

on:
  push:
    branches: [ "test" ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
     # To build the project.
      run: docker-compose build 
