name: Pull

# Only trigger, when the pull workflow succeeded
on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  notify:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Deploy Image
        run: sudo docker-compose pull
