name: Test
on:
  push:
    branches: [ "main" ]
jobs:
  notify:
    runs-on: self-hosted

    steps:
      - id: permission
        run: sudo chown -R $USER:$USER /home/ubuntu/actions-runner/_work/amtechtest
        
      - uses: actions/checkout@v3
      - name: update vm
        run: sudo apt-get update  
      
      - name: install docker
        run: sudo apt install -y docker-compose 

      - name: docker stop
        # stop and down all the containers running..
        run: sudo docker-compose down

      - id: image-css-frontend 
        run: |
              echo "images=$(sudo docker images  --filter=reference='ccs-frontend' --format  "{{.Repository}}")" >> "$GITHUB_OUTPUT"
              
      - name: image remove css-forntend
        env:
               images: ${{ steps.image-css-frontend.outputs.images }}
        run: |
              if [[ "$images" == "ccs-frontend" ]]; then
                   echo "Deleting ccs-frontend ..."
                     sudo docker image rm ccs-frontend
              else
                   echo "Image $image is not available locally."
              fi
     
      - name: image remove css-backend
        run: |
              echo "images=$(sudo docker images  --filter=reference='ccs-backend' --format  "{{.Repository}}")" >> "$GITHUB_OUTPUT"
              if [[ "$images" == "ccs-backend" ]]; then
                   echo "Deleting ccs-backend ..."
                     sudo docker image rm ccs-backend
              else
                   echo "Image $image is not available locally."
              fi    
       
      - name: image remove amtechtest_nginx
        run: |
              echo "images=$(sudo docker images  --filter=reference='"amtechtest_nginx' --format  "{{.Repository}}")" >> "$GITHUB_OUTPUT"
              if [[ "$images" == "amtechtest_nginx" ]]; then
                   echo "Deleting amtechtest_nginx ..."
                     sudo docker image rm amtechtest_nginx
              else
                      echo "Image $image is not available locally."
              fi
                     
      - name: image remove ws-server
        run: |
              echo "images=$(sudo docker images  --filter=reference='ws-server' --format  "{{.Repository}}")" >> "$GITHUB_OUTPUT"
              if [[ "$images" == " ws-server" ]]; then
                   echo "Deleting ws-server ..."
                     sudo docker image rm ws-server
              else
                   echo "Image $image is not available locally."
               fi
               
      - name: image remove nginx 
       
        run: |
             echo "images=$(sudo docker images  --filter=reference='nginx' --format  "{{.Repository}}")" >> "$GITHUB_OUTPUT"
              if [[ "$images" == "nginx" ]]; then
                   echo "Deleting nginx ..."
                     sudo docker image rm nginx
              else
                    echo "Image $image is not available locally."
              fi
              
      - name: image remove grafana 
        run: |
               echo "images=$(sudo docker images  --filter=reference='grafana' --format  "{{.Repository}}")" >> "$GITHUB_OUTPUT"
                if [[ "$images" == "grafana" ]]; then
                   echo "Deleting grafana ..."
                     sudo docker image rm grafana
                else
                    echo "Image $image is not available locally."
                fi
                
      - name: docker start
        # start and up all the containers
        run: sudo docker-compose up -d


