name: Test

on:
  push:
    branches: [ "main" ]

  
jobs:
  notify:
    runs-on: self-hosted

    steps:
      
      - id: permission
        run: sudo chown -R $USER:$USER /home/ubuntu/actions-runner/_work/amtechtest
        
      - uses: actions/checkout@v3

      - name: update vm
        run: sudo apt-get update  
      
      - name: install docker
        run: sudo apt install -y docker-compose 

      - name: docker stop
        # stop and down all the containers running.
        run: sudo docker-compose down
     
      - name: List Docker Images
      - id: list_images
        run: |
             
              echo "images=$(sudo docker image ls) >> $GITHUB_OUTPUT
         
          
      - name: Delete Specific Images
        run: |
          images_to_delete="ccs-backend css-frontend amtechtest_nginx ws-server grafana/grafana nginx"
          images="${{ steps.list_images.outputs.images}}"
          for image in $images_to_delete; do
            if [[ "$images" == *"$image"* ]]; then
              echo "Deleting $image..."
              sudo docker image rm "$image"
            else
              echo "Image $image_name is not available locally.
            fi
          done 

      - name: docker start
        # start and up all the containers
        run: sudo docker-compose up -d


